@baseUrl = http://localhost:4000


### GET /cards
GET {{baseUrl}}/api/cards

### GET /api/cards/:id
GET {{baseUrl}}/api/cards/1

### GET /api/cards/2000 (should not be found)
GET {{baseUrl}}/api/cards/2000

### POST /api/cards
POST http://localhost:4000/api/cards
Content-Type: application/json

{
  "text": "loremLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy",
  "author": "Martin",
  "votes": 0
}

### PATCH /api/cards/1
PATCH {{baseUrl}}/api/cards/1
Content-Type: application/json

{
  "text": "And now the body should be different"
}

### DELETE /api/users/1
DELETE {{baseUrl}}/api/cards/60b0fef249ae2490dc127232